#!/bin/bash
# 将包从16传输到41主机
# 需要提供41主机的正确SSH密码

echo "=== 传输包到10.1.81.41 ==="
echo ""
echo "包已准备在16主机: /tmp/mysql_packages.tar.gz (58MB)"
echo ""
echo "请提供10.1.81.41的SSH密码，然后执行："
echo ""
echo "方式1: 使用sshpass（如果已安装）"
echo "  sshpass -p 'YOUR_PASSWORD' scp root@10.1.81.16:/tmp/mysql_packages.tar.gz /tmp/"
echo "  sshpass -p 'YOUR_PASSWORD' scp /tmp/mysql_packages.tar.gz root@10.1.81.41:/opt/packet/"
echo "  sshpass -p 'YOUR_PASSWORD' ssh root@10.1.81.41 'cd /opt/packet && tar xzf mysql_packages.tar.gz && ls -lh'"
echo ""
echo "方式2: 手动输入密码"
echo "  scp root@10.1.81.16:/tmp/mysql_packages.tar.gz /tmp/"
echo "  scp /tmp/mysql_packages.tar.gz root@10.1.81.41:/opt/packet/"
echo "  ssh root@10.1.81.41 'cd /opt/packet && tar xzf mysql_packages.tar.gz && ls -lh'"
echo ""
echo "方式3: 如果有跳板机或其他访问路径"
echo "  请提供访问方式，我将调整脚本"
echo ""
echo "=== 当前41主机访问失败原因 ==="
echo "SSH返回: Permission denied (publickey,password)"
echo "尝试的密码: hcfc!2017"
echo "可能原因:"
echo "  1. 密码不正确"
echo "  2. 41主机仅允许密钥认证"
echo "  3. 41主机SSH配置限制了认证方式"
echo ""
echo "=== 需要的信息 ==="
echo "1. 41主机的正确SSH密码，或"
echo "2. 41主机的SSH私钥，或"
echo "3. 其他访问41主机的方式（跳板机、VPN等）"
