package executor

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// CgroupConfig 定义 systemd drop-in 配置参数
type CgroupConfig struct {
	Port          int    // MySQL 实例端口
	MemoryLimitMB int    // 内存限制（MB），0 使用默认值
	CPUQuotaPct   int    // CPU 配额百分比，0 使用默认值
	ServiceName   string // 自定义 systemd service 名称（可选，默认 mysqld_<port>）
}

// CgroupManager 负责为 MySQL 实例生成 systemd 资源限制配置（Cgroup v2）
// 通过 systemd drop-in 注入 MemoryMax 和 CPUQuota，防止单机多实例资源抢占
type CgroupManager struct {
	DefaultMemoryPercent  int // 默认内存限制百分比（实例内存的 %）
	DefaultCPUMultiplier int // 默认 CPU 配额乘数（核心数 × 此值）
}

// NewCgroupManager 创建 Cgroup 管理器
func NewCgroupManager() *CgroupManager {
	return &CgroupManager{
		DefaultMemoryPercent:  70,
		DefaultCPUMultiplier: 100,
	}
}

// serviceName 返回 systemd service 名称
func (m *CgroupManager) serviceName(cfg CgroupConfig) string {
	if cfg.ServiceName != "" {
		return cfg.ServiceName
	}
	return fmt.Sprintf("mysqld_%d", cfg.Port)
}

// GenerateSystemdOverride 生成并写入 systemd drop-in 配置文件
// 返回 (override目录路径, 配置文件路径, error)
//
// 输出路径：
//   /etc/systemd/system/<service>.service.d/limits.conf
//
// 内容：
//   [Service]
//   MemoryMax=<M>M
//   CPUQuota=<P>%
func (m *CgroupManager) GenerateSystemdOverride(cfg CgroupConfig) (string, string, error) {
	if cfg.Port <= 0 {
		return "", "", fmt.Errorf("invalid port: %d", cfg.Port)
	}

	svcName := m.serviceName(cfg)
	overrideDir := filepath.Join("/etc/systemd/system", fmt.Sprintf("%s.service.d", svcName))
	overrideFile := filepath.Join(overrideDir, "limits.conf")

	memoryLimit := cfg.MemoryLimitMB
	if memoryLimit <= 0 {
		memoryLimit = m.getDefaultMemoryLimit()
	}

	cpuQuota := cfg.CPUQuotaPct
	if cpuQuota <= 0 {
		cpuQuota = m.getDefaultCPUQuota()
	}

	// Build content
	var sb strings.Builder
	sb.WriteString("# Generated by dbops-agent CgroupManager\n")
	sb.WriteString(fmt.Sprintf("# Resource limits for MySQL instance on port %d\n", cfg.Port))
	sb.WriteString("\n[Service]\n")
	sb.WriteString(fmt.Sprintf("MemoryMax=%dM\n", memoryLimit))
	sb.WriteString(fmt.Sprintf("CPUQuota=%d%%\n", cpuQuota))

	// Ensure directory exists
	if err := os.MkdirAll(overrideDir, 0755); err != nil {
		return "", "", fmt.Errorf("create override dir %s failed: %w", overrideDir, err)
	}

	// Write file
	if err := os.WriteFile(overrideFile, []byte(sb.String()), 0644); err != nil {
		return "", "", fmt.Errorf("write override file %s failed: %w", overrideFile, err)
	}

	return overrideDir, overrideFile, nil
}

// WriteSystemdOverride 是 GenerateSystemdOverride 的别名，保持 API 一致性
func (m *CgroupManager) WriteSystemdOverride(port int, memoryLimitMB int, cpuQuotaPercent int) (string, error) {
	_, file, err := m.GenerateSystemdOverride(CgroupConfig{
		Port:          port,
		MemoryLimitMB: memoryLimitMB,
		CPUQuotaPct:   cpuQuotaPercent,
	})
	if err != nil {
		return "", err
	}
	return file, nil
}

// ReloadSystemd 执行 systemctl daemon-reload 使配置生效
func (m *CgroupManager) ReloadSystemd() error {
	if runtime.GOOS != "linux" {
		return fmt.Errorf("systemd reload is only supported on Linux")
	}

	cmd := exec.Command("systemctl", "daemon-reload")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("systemctl daemon-reload failed: %v, output: %s", err, strings.TrimSpace(string(output)))
	}

	return nil
}

// GenerateOverrideContent 只生成配置内容字符串，不写入文件
// 用于预览或测试
func (m *CgroupManager) GenerateOverrideContent(port int, memoryLimitMB int, cpuQuotaPercent int) string {
	if memoryLimitMB <= 0 {
		memoryLimitMB = m.getDefaultMemoryLimit()
	}
	if cpuQuotaPercent <= 0 {
		cpuQuotaPercent = m.getDefaultCPUQuota()
	}

	var sb strings.Builder
	sb.WriteString("# Generated by dbops-agent CgroupManager\n")
	sb.WriteString(fmt.Sprintf("# Resource limits for MySQL instance on port %d\n", port))
	sb.WriteString("\n[Service]\n")
	sb.WriteString(fmt.Sprintf("MemoryMax=%dM\n", memoryLimitMB))
	sb.WriteString(fmt.Sprintf("CPUQuota=%d%%\n", cpuQuotaPercent))

	return sb.String()
}

// getDefaultMemoryLimit 获取默认内存限制值
// 默认：实例内存的 70%（最小值 512MB）
func (m *CgroupManager) getDefaultMemoryLimit() int {
	if runtime.GOOS == "linux" {
		if data, err := os.ReadFile("/proc/meminfo"); err == nil {
			content := string(data)
			for _, line := range strings.Split(content, "\n") {
				if strings.HasPrefix(line, "MemTotal:") {
					parts := strings.Fields(line)
					if len(parts) >= 2 {
						var memKB int
						fmt.Sscanf(parts[1], "%d", &memKB)
						memMB := memKB / 1024
						defaultLimit := memMB * m.DefaultMemoryPercent / 100
						if defaultLimit < 512 {
							return 512
						}
						return defaultLimit
					}
				}
			}
		}
	}
	return 2048
}

// getDefaultCPUQuota 获取默认 CPU 配额百分比
// 默认：CPU 核心数 × 100%
func (m *CgroupManager) getDefaultCPUQuota() int {
	cpuCores := runtime.NumCPU()
	if cpuCores < 1 {
		cpuCores = 1
	}
	return cpuCores * m.DefaultCPUMultiplier
}

// CalculateMemoryLimit 计算每个实例的内存限制（MB）
// totalMemoryMB: 总内存（MB）
// instanceCount: 实例数（0 或 1 表示单实例，使用 70%）
// 返回最小值 256MB
func CalculateMemoryLimit(totalMemoryMB int, instanceCount int) int {
	if instanceCount <= 0 {
		instanceCount = 1
	}
	perInstance := totalMemoryMB / instanceCount
	limit := perInstance * 70 / 100
	if limit < 256 {
		return 256
	}
	return limit
}

// CalculateCPUQuota 计算 CPU 配额百分比
// cpuCores: CPU 核心数
// 返回核心数 × 100%
func CalculateCPUQuota(cpuCores int) int {
	if cpuCores < 1 {
		cpuCores = 1
	}
	return cpuCores * 100
}
