package repositories

import (
	"context"
	"time"

	"github.com/jackcode/mysql-ops-platform/internal/models"
)

var presetTemplates = []models.ParameterTemplate{
	{
		Name:        "small-instance",
		Description: "适用于小型实例（1-4GB 内存）的参数模板，优化资源使用和响应时间",
		Category:    string(models.PresetCategorySmall),
		IsPreset:    true,
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		Name:        "medium-instance",
		Description: "适用于中型实例（4-16GB 内存）的参数模板，平衡性能和资源消耗",
		Category:    string(models.PresetCategoryMedium),
		IsPreset:    true,
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		Name:        "large-instance",
		Description: "适用于大型实例（16-64GB 内存）的参数模板，最大化吞吐量和并发性能",
		Category:    string(models.PresetCategoryLarge),
		IsPreset:    true,
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		Name:        "memory-optimized",
		Description: "内存优化模板，适用于内存受限或需要最大化内存利用的场景",
		Category:    string(models.PresetCategoryMemoryOpt),
		IsPreset:    true,
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		Name:        "oltp-workload",
		Description: "OLTP 工作负载模板，优化事务处理、短查询和高并发写入",
		Category:    string(models.PresetCategoryOLTP),
		IsPreset:    true,
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		Name:        "olap-workload",
		Description: "OLAP 工作负载模板，优化分析查询、大表扫描和复杂聚合",
		Category:    string(models.PresetCategoryOLAP),
		IsPreset:    true,
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
}

var presetTemplateParameters = map[string][]models.ParameterTemplateParameter{
	"small-instance": []models.ParameterTemplateParameter{
		{
			ParameterName: "innodb_buffer_pool_size",
			Value:         "128M",
			DataType:      string(models.DataTypeSize),
			Description:   "InnoDB 缓冲池大小，建议设置为总内存的 50-70%",
			IsDynamic:     false,
			Category:      "memory",
		},
		{
			ParameterName: "innodb_log_file_size",
			Value:         "32M",
			DataType:      string(models.DataTypeSize),
			Description:   "InnoDB 日志文件大小",
			IsDynamic:     false,
			Category:      "memory",
		},
		{
			ParameterName: "max_connections",
			Value:         "100",
			DataType:      string(models.DataTypeInt),
			MinValue:      "10",
			MaxValue:      "500",
			Description:   "最大连接数",
			IsDynamic:     true,
			Category:      "connection",
		},
		{
			ParameterName: "query_cache_size",
			Value:         "0",
			DataType:      string(models.DataTypeSize),
			Description:   "查询缓存大小（MySQL 5.7 建议关闭）",
			IsDynamic:     true,
			Category:      "cache",
		},
		{
			ParameterName: "innodb_flush_log_at_trx_commit",
			Value:         "1",
			DataType:      string(models.DataTypeInt),
			MinValue:      "0",
			MaxValue:      "2",
			Description:   "事务提交时的日志刷新策略（1=最安全，2=性能更好）",
			IsDynamic:     true,
			Category:      "transaction",
		},
		{
			ParameterName: "sync_binlog",
			Value:         "1",
			DataType:      string(models.DataTypeInt),
			MinValue:      "0",
			MaxValue:      "1",
			Description:   "二进制日志同步策略（1=最安全）",
			IsDynamic:     true,
			Category:      "replication",
		},
		{
			ParameterName: "innodb_flush_method",
			Value:         "O_DIRECT",
			DataType:      string(models.DataTypeString),
			Description:   "InnoDB 数据刷新方法",
			IsDynamic:     false,
			Category:      "storage",
		},
		{
			ParameterName: "table_open_cache",
			Value:         "400",
			DataType:      string(models.DataTypeInt),
			Description:   "表缓存数量",
			IsDynamic:     true,
			Category:      "cache",
		},
	},
	"medium-instance": []models.ParameterTemplateParameter{
		{
			ParameterName: "innodb_buffer_pool_size",
			Value:         "512M",
			DataType:      string(models.DataTypeSize),
			Description:   "InnoDB 缓冲池大小，建议设置为总内存的 50-70%",
			IsDynamic:     false,
			Category:      "memory",
		},
		{
			ParameterName: "innodb_log_file_size",
			Value:         "128M",
			DataType:      string(models.DataTypeSize),
			Description:   "InnoDB 日志文件大小",
			IsDynamic:     false,
			Category:      "memory",
		},
		{
			ParameterName: "max_connections",
			Value:         "200",
			DataType:      string(models.DataTypeInt),
			MinValue:      "10",
			MaxValue:      "1000",
			Description:   "最大连接数",
			IsDynamic:     true,
			Category:      "connection",
		},
		{
			ParameterName: "innodb_flush_log_at_trx_commit",
			Value:         "1",
			DataType:      string(models.DataTypeInt),
			MinValue:      "0",
			MaxValue:      "2",
			Description:   "事务提交时的日志刷新策略",
			IsDynamic:     true,
			Category:      "transaction",
		},
		{
			ParameterName: "innodb_io_capacity",
			Value:         "200",
			DataType:      string(models.DataTypeInt),
			Description:   "InnoDB I/O 容量",
			IsDynamic:     true,
			Category:      "storage",
		},
		{
			ParameterName: "innodb_io_capacity_max",
			Value:         "400",
			DataType:      string(models.DataTypeInt),
			Description:   "InnoDB 最大 I/O 容量",
			IsDynamic:     true,
			Category:      "storage",
		},
		{
			ParameterName: "table_open_cache",
			Value:         "800",
			DataType:      string(models.DataTypeInt),
			Description:   "表缓存数量",
			IsDynamic:     true,
			Category:      "cache",
		},
		{
			ParameterName: "thread_cache_size",
			Value:         "16",
			DataType:      string(models.DataTypeInt),
			Description:   "线程缓存大小",
			IsDynamic:     true,
			Category:      "connection",
		},
	},
	"large-instance": []models.ParameterTemplateParameter{
		{
			ParameterName: "innodb_buffer_pool_size",
			Value:         "16G",
			DataType:      string(models.DataTypeSize),
			Description:   "InnoDB 缓冲池大小，建议设置为总内存的 50-70%（16–64GB 内存约 16G 起）",
			IsDynamic:     false,
			Category:      "memory",
		},
		{
			ParameterName: "innodb_log_file_size",
			Value:         "1G",
			DataType:      string(models.DataTypeSize),
			Description:   "InnoDB 日志文件大小",
			IsDynamic:     false,
			Category:      "memory",
		},
		{
			ParameterName: "innodb_buffer_pool_instances",
			Value:         "8",
			DataType:      string(models.DataTypeInt),
			MinValue:      "1",
			MaxValue:      "64",
			Description:   "InnoDB 缓冲池实例数量（大内存时减少锁竞争）",
			IsDynamic:     false,
			Category:      "memory",
		},
		{
			ParameterName: "max_connections",
			Value:         "500",
			DataType:      string(models.DataTypeInt),
			MinValue:      "10",
			MaxValue:      "5000",
			Description:   "最大连接数",
			IsDynamic:     true,
			Category:      "connection",
		},
		{
			ParameterName: "innodb_flush_log_at_trx_commit",
			Value:         "1",
			DataType:      string(models.DataTypeInt),
			MinValue:      "0",
			MaxValue:      "2",
			Description:   "事务提交时的日志刷新策略",
			IsDynamic:     true,
			Category:      "transaction",
		},
		{
			ParameterName: "innodb_io_capacity",
			Value:         "1000",
			DataType:      string(models.DataTypeInt),
			Description:   "InnoDB I/O 容量",
			IsDynamic:     true,
			Category:      "storage",
		},
		{
			ParameterName: "innodb_io_capacity_max",
			Value:         "2000",
			DataType:      string(models.DataTypeInt),
			Description:   "InnoDB 最大 I/O 容量",
			IsDynamic:     true,
			Category:      "storage",
		},
		{
			ParameterName: "table_open_cache",
			Value:         "2000",
			DataType:      string(models.DataTypeInt),
			Description:   "表缓存数量",
			IsDynamic:     true,
			Category:      "cache",
		},
		{
			ParameterName: "thread_cache_size",
			Value:         "64",
			DataType:      string(models.DataTypeInt),
			Description:   "线程缓存大小",
			IsDynamic:     true,
			Category:      "connection",
		},
		{
			ParameterName: "innodb_read_io_threads",
			Value:         "8",
			DataType:      string(models.DataTypeInt),
			MinValue:      "1",
			MaxValue:      "64",
			Description:   "InnoDB 读 I/O 线程数",
			IsDynamic:     false,
			Category:      "thread",
		},
		{
			ParameterName: "innodb_write_io_threads",
			Value:         "8",
			DataType:      string(models.DataTypeInt),
			MinValue:      "1",
			MaxValue:      "64",
			Description:   "InnoDB 写 I/O 线程数",
			IsDynamic:     false,
			Category:      "thread",
		},
	},
	"memory-optimized": []models.ParameterTemplateParameter{
		{
			ParameterName: "innodb_buffer_pool_size",
			Value:         "4G",
			DataType:      string(models.DataTypeSize),
			Description:   "InnoDB 缓冲池大小",
			IsDynamic:     false,
			Category:      "memory",
		},
		{
			ParameterName: "innodb_log_buffer_size",
			Value:         "64M",
			DataType:      string(models.DataTypeSize),
			Description:   "InnoDB 日志缓冲区大小",
			IsDynamic:     true,
			Category:      "memory",
		},
		{
			ParameterName: "innodb_sort_buffer_size",
			Value:         "2M",
			DataType:      string(models.DataTypeSize),
			Description:   "InnoDB 排序缓冲区大小",
			IsDynamic:     true,
			Category:      "memory",
		},
		{
			ParameterName: "join_buffer_size",
			Value:         "256K",
			DataType:      string(models.DataTypeSize),
			Description:   "JOIN 操作缓冲区大小",
			IsDynamic:     true,
			Category:      "memory",
		},
		{
			ParameterName: "sort_buffer_size",
			Value:         "256K",
			DataType:      string(models.DataTypeSize),
			Description:   "排序缓冲区大小",
			IsDynamic:     true,
			Category:      "memory",
		},
		{
			ParameterName: "read_buffer_size",
			Value:         "128K",
			DataType:      string(models.DataTypeSize),
			Description:   "读取缓冲区大小",
			IsDynamic:     true,
			Category:      "memory",
		},
		{
			ParameterName: "read_rnd_buffer_size",
			Value:         "256K",
			DataType:      string(models.DataTypeSize),
			Description:   "随机读取缓冲区大小",
			IsDynamic:     true,
			Category:      "memory",
		},
		{
			ParameterName: "tmp_table_size",
			Value:         "64M",
			DataType:      string(models.DataTypeSize),
			Description:   "临时表最大大小",
			IsDynamic:     true,
			Category:      "memory",
		},
		{
			ParameterName: "max_heap_table_size",
			Value:         "64M",
			DataType:      string(models.DataTypeSize),
			Description:   "MEMORY 表最大大小",
			IsDynamic:     true,
			Category:      "memory",
		},
	},
	"oltp-workload": []models.ParameterTemplateParameter{
		{
			ParameterName: "innodb_buffer_pool_size",
			Value:         "4G",
			DataType:      string(models.DataTypeSize),
			Description:   "InnoDB 缓冲池大小",
			IsDynamic:     false,
			Category:      "memory",
		},
		{
			ParameterName: "innodb_flush_log_at_trx_commit",
			Value:         "1",
			DataType:      string(models.DataTypeInt),
			MinValue:      "0",
			MaxValue:      "2",
			Description:   "事务提交时日志刷新策略（OLTP 建议 1）",
			IsDynamic:     true,
			Category:      "transaction",
		},
		{
			ParameterName: "sync_binlog",
			Value:         "1",
			DataType:      string(models.DataTypeInt),
			MinValue:      "0",
			MaxValue:      "1",
			Description:   "二进制日志同步策略（OLTP 建议 1）",
			IsDynamic:     true,
			Category:      "replication",
		},
		{
			ParameterName: "innodb_lock_wait_timeout",
			Value:         "5",
			DataType:      string(models.DataTypeInt),
			MinValue:      "1",
			MaxValue:      "3600",
			Unit:          "seconds",
			Description:   "InnoDB 锁等待超时时间（OLTP 建议短超时）",
			IsDynamic:     true,
			Category:      "transaction",
		},
		{
			ParameterName: "max_connections",
			Value:         "300",
			DataType:      string(models.DataTypeInt),
			Description:   "最大连接数",
			IsDynamic:     true,
			Category:      "connection",
		},
		{
			ParameterName: "thread_cache_size",
			Value:         "32",
			DataType:      string(models.DataTypeInt),
			Description:   "线程缓存大小",
			IsDynamic:     true,
			Category:      "connection",
		},
		{
			ParameterName: "innodb_thread_concurrency",
			Value:         "0",
			DataType:      string(models.DataTypeInt),
			MinValue:      "0",
			MaxValue:      "1000",
			Description:   "InnoDB 线程并发限制（0=无限制）",
			IsDynamic:     true,
			Category:      "thread",
		},
		{
			ParameterName: "transaction_isolation",
			Value:         "READ-COMMITTED",
			DataType:      string(models.DataTypeString),
			Description:   "事务隔离级别",
			IsDynamic:     true,
			Category:      "transaction",
		},
	},
	"olap-workload": []models.ParameterTemplateParameter{
		{
			ParameterName: "innodb_buffer_pool_size",
			Value:         "8G",
			DataType:      string(models.DataTypeSize),
			Description:   "InnoDB 缓冲池大小（OLAP 需要较大缓冲）",
			IsDynamic:     false,
			Category:      "memory",
		},
		{
			ParameterName: "innodb_flush_log_at_trx_commit",
			Value:         "2",
			DataType:      string(models.DataTypeInt),
			MinValue:      "0",
			MaxValue:      "2",
			Description:   "事务提交时日志刷新策略（OLAP 可用 2）",
			IsDynamic:     true,
			Category:      "transaction",
		},
		{
			ParameterName: "sync_binlog",
			Value:         "0",
			DataType:      string(models.DataTypeInt),
			MinValue:      "0",
			MaxValue:      "1",
			Description:   "二进制日志同步策略（OLAP 可用 0）",
			IsDynamic:     true,
			Category:      "replication",
		},
		{
			ParameterName: "join_buffer_size",
			Value:         "4M",
			DataType:      string(models.DataTypeSize),
			Description:   "JOIN 操作缓冲区大小（OLAP 需要较大）",
			IsDynamic:     true,
			Category:      "memory",
		},
		{
			ParameterName: "sort_buffer_size",
			Value:         "4M",
			DataType:      string(models.DataTypeSize),
			Description:   "排序缓冲区大小（OLAP 需要较大）",
			IsDynamic:     true,
			Category:      "memory",
		},
		{
			ParameterName: "read_buffer_size",
			Value:         "2M",
			DataType:      string(models.DataTypeSize),
			Description:   "读取缓冲区大小（OLAP 需要较大）",
			IsDynamic:     true,
			Category:      "memory",
		},
		{
			ParameterName: "tmp_table_size",
		 Value:         "256M",
			DataType:      string(models.DataTypeSize),
			Description:   "临时表最大大小（OLAP 需要较大）",
			IsDynamic:     true,
			Category:      "memory",
		},
		{
			ParameterName: "max_heap_table_size",
			Value:         "256M",
			DataType:      string(models.DataTypeSize),
			Description:   "MEMORY 表最大大小",
			IsDynamic:     true,
			Category:      "memory",
		},
		{
			ParameterName: "long_query_time",
			Value:         "10",
			DataType:      string(models.DataTypeInt),
			MinValue:      "0",
			MaxValue:      "3600",
			Unit:          "seconds",
			Description:   "慢查询阈值（OLAP 可以较长）",
			IsDynamic:     true,
			Category:      "monitoring",
		},
		{
			ParameterName: "log_queries_not_using_indexes",
			Value:         "OFF",
			DataType:      string(models.DataTypeBool),
			Description:   "记录未使用索引的查询",
			IsDynamic:     true,
			Category:      "monitoring",
		},
	},
}

func SeedPresetTemplates(ctx context.Context, repo *ParameterTemplateRepository) error {
	for _, template := range presetTemplates {
		existing, err := repo.GetByName(ctx, template.Name)
		if err == nil && existing != nil {
			continue
		}

		if err := repo.Create(ctx, &template); err != nil {
			return err
		}

		params := presetTemplateParameters[template.Name]
		for _, param := range params {
			param.TemplateID = template.ID
			if err := repo.CreateParameter(ctx, &param); err != nil {
				return err
			}
		}

		version := &models.ParameterTemplateVersion{
			TemplateID:  template.ID,
			Version:     "1.0",
			Description: "初始版本",
			IsActive:    true,
			CreatedAt:   time.Now(),
		}
		if err := repo.CreateVersion(ctx, version); err != nil {
			return err
		}
	}

	return nil
}

func GetPresetTemplates() []models.ParameterTemplate {
	return presetTemplates
}